"""Emit the flat per-study JSON feed that research-digest-dashboard consumes.

That dashboard aggregates ~12 feeder repos, and its `sync-new-scientist.yml`
fetches this repo at a fixed raw URL:

    .../new-scientist-story-ideas/main/data/results.json

The previous pipeline wrote that file directly as its primary output. This one
writes markdown to `outputs/`, so the feed is regenerated from the same parsed
digests that build the local dashboard — one flat, PMID-deduplicated array of
every study ever written up, in the field names the aggregator's sync step
already maps (`ns_score` -> `relevance_score`, `ns_pitch` -> `pitch_angles`).

Keeping the path and the field names identical means the aggregator repo needs
no change. If you ever rename this output, `sync-new-scientist.yml` over there
has to be updated in the same breath or its daily run starts failing.
"""

import json
import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path

from build_dashboard_data import build
from journals import MIND_JOURNALS

REPO_ROOT = Path(__file__).parent.parent
FEED_PATH = REPO_ROOT / "data" / "results.json"

SOURCE_ID = "new-scientist-mh"
SOURCE_LABEL = "New Scientist — Mental Health"


def _norm(text: str) -> str:
    text = (text or "").lower().replace("&", " and ")
    text = re.sub(r"\([^)]*\)", " ", text)                      # "Emotion (Washington, D.C.)"
    text = unicodedata.normalize("NFD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = re.sub(r"^\s*the\s+", " ", text)
    return re.sub(r"[^a-z0-9]+", "", text)


def _build_journal_categories() -> tuple[dict, dict]:
    """Index the curated journal list by full title and by title-before-subtitle.

    PubMed's display name and the CSV's MEDLINE-style title disagree often
    enough ("Brain" vs "Brain : a journal of neurology") that an exact match
    alone only resolves about four fifths of studies.
    """
    exact: dict[str, str] = {}
    head: dict[str, str] = {}
    for title, _issn, cats in MIND_JOURNALS:
        if not cats:
            continue
        exact.setdefault(_norm(title), cats[0])
        head.setdefault(_norm(re.split(r"\s*[:.]\s", title)[0]), cats[0])
    return exact, head


_EXACT, _HEAD = _build_journal_categories()


def _category(journal: str, topic: str) -> str:
    """The journal's primary NLM category, falling back to the digest's topic.

    Category drives a filter dropdown on the aggregator, so an empty value would
    quietly drop the study out of any category-filtered view.
    """
    key = _norm(journal)
    if key in _EXACT:
        return _EXACT[key]
    if key in _HEAD:
        return _HEAD[key]
    if len(key) >= 6:
        candidates = {v for k, v in _EXACT.items() if k.startswith(key)}
        if len(candidates) == 1:
            return candidates.pop()
    return topic.title() if topic else "Mental Health"


def _pitch_angles(study: dict) -> list[dict]:
    """Map the two story angles onto the aggregator's array-of-pitches shape.

    The aggregator merges pitches across feeds by `headline`, so the two entries
    carry distinct headlines — otherwise a study that also appears in another
    feed can lose one of them in the merge.
    """
    angles = []
    if study.get("pitch_angle"):
        angles.append({
            "publication_type": "New Scientist Mind",
            "headline": study["title"],
            "hook": study.get("why_it_matters", ""),
            "pitch_angle": study["pitch_angle"],
            "why_it_fits": study.get("ns_score_reason", ""),
            "caveats_to_flag": study.get("caveats", ""),
        })
    wider = study.get("wider_angle", "")
    if wider and "not generated by the previous pipeline" not in wider.lower():
        angles.append({
            "publication_type": "Wider angle — elsewhere",
            "headline": f"{study['title']} (wider angle)",
            "hook": "",
            "pitch_angle": wider,
            "why_it_fits": "",
            "caveats_to_flag": study.get("caveats", ""),
        })
    return angles


def _flatten(run: dict, study: dict) -> dict:
    fact_check = run.get("fact_check") or {}
    verdict = (fact_check.get("verdicts_by_pmid") or {}).get(study.get("pmid"), "")
    return {
        "pmid": study.get("pmid", ""),
        "headline": study.get("title", ""),
        "journal": study.get("journal", ""),
        "pubdate": study.get("published", ""),
        "doi": study.get("doi", ""),
        "category": _category(study.get("journal", ""), run.get("topic", "")),
        "groundbreaking": study.get("novelty", ""),
        "media_coverage": study.get("media_check", ""),
        "summary": study.get("the_study", ""),
        "why_it_matters": study.get("why_it_matters", ""),
        "caveats": study.get("caveats", ""),
        "fact_check_note": verdict,
        "excluded": False,
        "ns_score": study.get("ns_score"),
        "ns_score_reason": study.get("ns_score_reason", ""),
        # `pitch_angles` is emitted directly rather than the old nested `ns_pitch`;
        # the sync step only converts `ns_pitch` when `pitch_angles` is absent.
        "pitch_angles": _pitch_angles(study),
        "run_date": run.get("run_date", ""),
        "status": "new",
    }


def build_feed() -> dict:
    runs = build()          # newest first

    # Newest run wins on a repeated PMID: a later digest's write-up supersedes
    # an earlier one, and the aggregator only ever sees one entry per study.
    by_pmid: dict[str, dict] = {}
    for run in runs:
        for study in run["studies"]:
            pmid = study.get("pmid")
            if pmid and pmid not in by_pmid:
                by_pmid[pmid] = _flatten(run, study)

    studies = list(by_pmid.values())
    newest_date = runs[0]["run_date"] if runs else ""
    new_this_run = sum(1 for s in studies if s["run_date"] == newest_date)

    return {
        "last_updated": datetime.now(timezone.utc).isoformat(),
        "source_id": SOURCE_ID,
        "source_label": SOURCE_LABEL,
        "total_studies": len(studies),
        "new_this_run": new_this_run,
        "studies": studies,
    }


def main() -> None:
    feed = build_feed()
    FEED_PATH.parent.mkdir(parents=True, exist_ok=True)
    FEED_PATH.write_text(json.dumps(feed, indent=2) + "\n", encoding="utf-8")
    uncategorised = sum(1 for s in feed["studies"] if not s["category"])
    print(
        f"Wrote {feed['total_studies']} studies to {FEED_PATH.relative_to(REPO_ROOT)} "
        f"({feed['new_this_run']} from the latest run)"
        + (f"; {uncategorised} with no category" if uncategorised else "")
    )


if __name__ == "__main__":
    main()
