"""Mental health and brain science journal ISSNs, generated from
`data/Mental Health - Brain Mental Health.csv`.

Regenerate with `python3 scripts/build_journals.py` after editing the CSV.
"""

# (journal_name, issn, [NLM categories]) — prefers the electronic ISSN,
# falls back to print. Rows with no ISSN at all are dropped.
MIND_JOURNALS: list[tuple[str, str, list[str]]] = [
    ('Biopsychosocial science and medicine', '2998-8756', ['Psychiatry', 'Psychology']),
    ('Spanish journal of psychiatry and mental health', '2950-2853', ['Psychiatry', 'Psychology']),
    ('BMJ mental health', '2755-9734', ['Psychology']),
    ('Journal of psychopathology and clinical science', '2769-755X', ['Psychology']),
    ('Nature human behaviour', '2397-3374', ['Behavioral Sciences', 'Psychology']),
    ('Revista Colombiana de psiquiatría', '2530-3120', ['Psychiatry']),
    ('Cognitive research: principles and implications', '2365-7464', ['Psychology']),
    ('New directions for student leadership', '2373-3357', ['Psychiatry', 'Psychology']),
    ('Current opinion in psychology', '2352-2518', ['Psychology']),
    ('Sleep health', '2352-7226', ['Psychophysiology']),
    ('Journal of experimental psychology. Animal learning and cognition', '2329-8464', ['Behavioral Sciences', 'Psychology']),
    ('LGBT health', '2325-8306', ['Behavioral Sciences', 'Public Health']),
    ('eNeuro', '2373-2822', ['Brain', 'Neurology']),
    ('The lancet. Psychiatry', '2215-0374', ['Psychiatry']),
    ('JAMA psychiatry', '2168-6238', ['Psychiatry', 'Psychology']),
    ('BMC psychology', '2050-7283', ['Psychology']),
    ('Journal of behavioral addictions', '2063-5303', ['Behavioral Sciences', 'Psychiatry']),
    ('Psychodynamic psychiatry', '2162-2604', ['Psychiatry']),
    ('Games for health journal', '2161-7856', ['Psychology']),
    ('PsyCh journal', '2046-0260', ['Psychology']),
    ('Brain and behavior', '2162-3279', ['Behavioral Sciences', 'Brain']),
    ('Translational behavioral medicine', '1613-9860', ['Behavioral Sciences', 'Medicine', 'Public Health']),
    ('Brain connectivity', '2158-0022', ['Brain', 'Neurology']),
    ('Fluids and barriers of the CNS', '2045-8118', ['Brain', 'Neurology']),
    ('Trends in psychiatry and psychotherapy', '2238-0019', ['Psychiatry']),
    ('Translational psychiatry', '2158-3188', ['Psychiatry']),
    ('Pain management', '1758-1877', ['Psychophysiology']),
    ('Cyberpsychology, behavior and social networking', '2152-2723', ['Behavioral Sciences', 'Psychology']),
    ('East Asian archives of psychiatry : official journal of the Hong Kong College of Psychiatrists = Dong Ya jing shen ke xue zhi : Xianggang jing shen ke yi xue yuan qi kan', '2224-7041', ['Psychiatry']),
    ('European journal of psychotraumatology', '2000-8066', ['Psychiatry', 'Psychology']),
    ('Personality disorders', '1949-2723', ['Psychology']),
    ('Wiley interdisciplinary reviews. Cognitive science', '1939-5086', ['Psychology']),
    ('Current topics in behavioral neurosciences', '1866-3389', ['Behavioral Sciences', 'Neurology']),
    ('Applied psychology. Health and well-being', '1758-0854', ['Behavioral Sciences', 'Psychology']),
    ('Longitudinal and life course studies : international journal', '1757-9597', ['Behavioral Sciences', 'Public Health', 'Social Sciences']),
    ('Asia-Pacific psychiatry : official journal of the Pacific Rim College of Psychiatrists', '1758-5872', ['Psychiatry']),
    ('American journal on intellectual and developmental disabilities', '1944-7558', ['Psychiatry']),
    ('Topics in cognitive science', '1756-8765', ['Psychology']),
    ('Psychological trauma : theory, research, practice and policy', '1942-969X', ['Psychology']),
    ('Attention, perception & psychophysics', '1943-393X', ['Psychology', 'Psychophysiology']),
    ('Scandinavian journal of pain', '1877-8879', ['Psychophysiology']),
    ('Autism research : official journal of the International Society for Autism Research', '1939-3806', ['Psychiatry']),
    ('Asian journal of psychiatry', '1876-2026', ['Psychiatry']),
    ('Sexual development : genetics, molecular biology, evolution, endocrinology, embryology, and pathology of sex determination and differentiation', '1661-5433', ['Behavioral Sciences']),
    ('Brain imaging and behavior', '1931-7565', ['Behavioral Sciences', 'Brain', 'Diagnostic Imaging']),
    ('Integrative psychological & behavioral science', '1936-3567', ['Behavioral Sciences', 'Psychology']),
    ('Health psychology review', '1743-7202', ['Behavioral Sciences', 'Psychology']),
    ('Frontiers in neural circuits', '1662-5110', ['Brain', 'Neurology']),
    ('Early intervention in psychiatry', '1751-7893', ['Psychiatry']),
    ('Intellectual and developmental disabilities', '1934-9556', ['Psychiatry']),
    ('Personality and mental health', '1932-863X', ['Psychiatry', 'Psychology']),
    ('Perspectives on psychological science : a journal of the Association for Psychological Science', '1745-6924', ['Psychology']),
    ('The quarterly journal of experimental psychology : QJEP', '1747-0226', ['Psychology', 'Psychophysiology']),
    ('Sleep medicine clinics', '1556-4088', ['Psychophysiology']),
    ('Behavior research methods', '1554-3528', ['Behavioral Sciences']),
    ('Behavioral and brain functions : BBF', '1744-9081', ['Behavioral Sciences', 'Brain']),
    ('Journal of intellectual disabilities : JOID', '1744-6309', ['Psychiatry']),
    ('Annual review of clinical psychology', '1548-5951', ['Psychology']),
    ('The international journal of behavioral nutrition and physical activity', '1479-5868', ['Behavioral Sciences', 'Nutritional Sciences', 'Sports Medicine']),
    ('Clinical EEG and neuroscience', '2169-5202', ['Brain', 'Neurology']),
    ('Journal of dual diagnosis', '1550-4271', ['Psychiatry', 'Substance-Related Disorders']),
    ('Body image', '1873-6807', ['Psychology']),
    ('Evolutionary psychology : an international journal of evolutionary approaches to psychology and behavior', '1474-7049', ['Behavioral Sciences', 'Biology', 'Psychology']),
    ('Behavioral sleep medicine', '1540-2010', ['Behavioral Sciences', 'Psychophysiology']),
    ('Learning & behavior', '1543-4508', ['Behavioral Sciences', 'Veterinary Medicine']),
    ('Journal of child and adolescent mental health', '1728-0591', ['Psychology']),
    ('Genes, brain, and behavior', '1601-183X', ['Behavioral Sciences', 'Brain', 'Genetics']),
    ('Journal of nutrition education and behavior', '1878-2620', ['Behavioral Sciences', 'Education', 'Nutritional Sciences']),
    ('Cognitive behaviour therapy', '1651-2316', ['Behavioral Sciences', 'Therapeutics']),
    ('Dementia', '1741-2684', ['Psychiatry']),
    ('Psychology and psychotherapy', '2044-8341', ['Psychiatry', 'Psychology', 'Therapeutics']),
    ('Experimental psychology', '2190-5142', ['Psychology']),
    ('The journal of pastoral care & counseling : JPCC', '2167-776X', ['Psychology']),
    ('Cognitive, affective & behavioral neuroscience', '1531-135X', ['Behavioral Sciences', 'Neurology']),
    ('Journal of comparative physiology. A, Neuroethology, sensory, neural, and behavioral physiology', '1432-1351', ['Behavioral Sciences', 'Neurology']),
    ('BMC psychiatry', '1471-244X', ['Psychiatry']),
    ('Stress and health : journal of the International Society for the Investigation of Stress', '1532-2998', ['Psychology']),
    ('Emotion', '1931-1516', ['Psychology']),
    ('Epilepsy & behavior : E&B', '1525-5069', ['Behavioral Sciences', 'Neurology']),
    ('Eating behaviors', '1873-7358', ['Behavioral Sciences', 'Nutritional Sciences']),
    ('Advances in life course research', '1879-6974', ['Behavioral Sciences', 'Social Sciences']),
    ('Brain impairment : a multidisciplinary journal of the Australian Society for the Study of Brain Impairment', '1839-5252', ['Brain', 'Neurology']),
    ('The world journal of biological psychiatry : the official journal of the World Federation of Societies of Biological Psychiatry', '1814-1412', ['Psychiatry']),
    ('Journal of psychiatric practice', '1538-1145', ['Psychiatry']),
    ('Cognitive processing', '1612-4790', ['Psychology']),
    ('Psychological science in the public interest : a journal of the American Psychological Society', '2160-0031', ['Psychology']),
    ('Psychology of sport and exercise', '1878-5476', ['Psychology', 'Sports Medicine']),
    ('Culture, health & sexuality', '1464-5351', ['Behavioral Sciences', 'Social Sciences']),
    ('Attachment & human development', '1469-2988', ['Behavioral Sciences', 'Social Sciences']),
    ('Epileptic disorders : international epilepsy journal with videotape', '1950-6945', ['Brain', 'Neurology']),
    ('Bipolar disorders', '1399-5618', ['Psychiatry']),
    ('Actas españolas de psiquiatría', '1578-2735', ['Psychiatry']),
    ('Current psychiatry reports', '1535-1645', ['Psychiatry']),
    ('Revista brasileira de psiquiatria : orgão oficial da Associação Brasileira de Psiquiatria, Asociación Psiquiátrica de la América Latina', '1809-452X', ['Psychiatry']),
    ('Nordic journal of psychiatry', '1502-4725', ['Psychiatry', 'Psychopharmacology']),
    ('Zeitschrift für Psychosomatische Medizin und Psychotherapie', '2196-8349', ['Psychiatry', 'Psychophysiology']),
    ('American Indian and Alaska native mental health research : the journal of the National Center', '1533-7731', ['Psychology']),
    ('Cultural diversity & ethnic minority psychology', '1099-9809', ['Psychology', 'Social Sciences']),
    ('The journal of behavioral health services & research', '1556-3308', ['Behavioral Sciences', 'Health Services', 'Health Services Research']),
    ('Developmental science', '1467-7687', ['Psychology']),
    ('The Spanish journal of psychology', '1988-2904', ['Psychology']),
    ("Archives of women's mental health", '1435-1102', ['Psychology', "Women's Health"]),
    ('Journal of lesbian studies', '1540-3548', ['Behavioral Sciences']),
    ('Health education & behavior : the official publication of the Society for Public Health Education', '1552-6127', ['Behavioral Sciences', 'Education', 'Public Health']),
    ('Applied psychophysiology and biofeedback', '1573-3270', ['Behavioral Sciences', 'Psychophysiology']),
    ('Transcultural psychiatry', '1461-7471', ['Psychiatry']),
    ('Depression and anxiety', '1520-6394', ['Psychiatry']),
    ('International journal of psychiatry in clinical practice', '1471-1788', ['Psychiatry']),
    ('Autism : the international journal of research and practice', '1461-7005', ['Psychiatry', 'Psychology']),
    ('Trends in cognitive sciences', '1879-307X', ['Psychology']),
    ('Personality and social psychology review : an official journal of the Society for Personality and Social Psychology, Inc', '1532-7957', ['Psychology', 'Social Sciences']),
    ('Journal of intellectual & developmental disability', '1469-9532', ['Psychiatry']),
    ('Journal of applied research in intellectual disabilities : JARID', '1468-3148', ['Psychiatry']),
    ('Journal of attention disorders', '1557-1246', ['Psychiatry']),
    ('British journal of health psychology', '2044-8287', ['Psychology']),
    ('Psychological methods', '1939-1463', ['Psychology']),
    ('Journal of health psychology', '1461-7277', ['Psychology']),
    ('Sleep & breathing = Schlaf & Atmung', '1522-1709', ['Psychophysiology', 'Pulmonary Medicine']),
    ('Archives of suicide research : official journal of the International Academy for Suicide Research', '1543-6136', ['Behavioral Sciences']),
    ('Neurobiology of learning and memory', '1095-9564', ['Behavioral Sciences', 'Biology', 'Neurology']),
    ('Neurocase', '1465-3656', ['Behavioral Sciences', 'Neurology', 'Psychiatry', 'Psychology']),
    ('Psychiatric rehabilitation journal', '1559-3126', ['Psychiatry']),
    ('Psychiatric services : a journal of the American Psychiatric Association', '1557-9700', ['Psychiatry']),
    ('Sexual abuse : a journal of research and treatment', '1573-286X', ['Psychiatry']),
    ('Journal of experimental psychology. Applied', '1939-2192', ['Psychology']),
    ('International journal of behavioral medicine', '1532-7558', ['Behavioral Sciences']),
    ('Assessment', '1552-3489', ['Psychology']),
    ('Journal of clinical psychology in medical settings', '1573-3572', ['Psychology']),
    ('Psychonomic bulletin & review', '1531-5320', ['Psychology']),
    ('Behavioural and cognitive psychotherapy', '1469-1833', ['Behavioral Sciences', 'Psychiatry']),
    ('Harvard review of psychiatry', '1465-7309', ['Psychiatry']),
    ('Clinical psychology & psychotherapy', '1099-0879', ['Psychiatry', 'Psychology', 'Therapeutics']),
    ('Memory', '1464-0686', ['Psychology']),
    ('Canadian journal of experimental psychology = Revue canadienne de psychologie expérimentale', '1878-7290', ['Psychology']),
    ('Experimental and clinical psychopharmacology', '1936-2293', ['Psychopharmacology']),
    ('Journal of child sexual abuse', '1547-0679', ['Behavioral Sciences', 'Psychiatry']),
    ('Anxiety, stress, and coping', '1477-2205', ['Behavioral Sciences', 'Psychology']),
    ('Journal of intellectual disability research : JIDR', '1365-2788', ['Psychiatry']),
    ('Journal of mental health', '1360-0567', ['Psychiatry', 'Psychology']),
    ('Consciousness and cognition', '1090-2376', ['Psychology', 'Psychophysiology']),
    ('Journal of sleep research', '1365-2869', ['Psychophysiology']),
    ('Criminal behaviour and mental health : CBMH', '1471-2857', ['Behavioral Sciences', 'Psychology']),
    ('Australasian psychiatry : bulletin of Royal Australian and New Zealand College of Psychiatrists', '1440-1665', ['Psychiatry']),
    ('International journal of methods in psychiatric research', '1557-0657', ['Psychiatry']),
    ('European psychiatry : the journal of the Association of European Psychiatrists', '1778-3585', ['Psychiatry']),
    ('Psychotherapy research : journal of the Society for Psychotherapy Research', '1468-4381', ['Psychiatry', 'Psychology', 'Therapeutics']),
    ('Brain pathology', '1750-3639', ['Brain', 'Pathology']),
    ('Türk psikiyatri dergisi = Turkish journal of psychiatry', '2651-3463', ['Psychiatry']),
    ('Vertex : revista argentina de psiquiatriá', '2718-904X', ['Psychiatry']),
    ('Journal of gambling studies', '1573-3602', ['Psychology']),
    ('Psychological science', '1467-9280', ['Psychology']),
    ('European neuropsychopharmacology : the journal of the European College of Neuropsychopharmacology', '1873-7862', ['Psychopharmacology']),
    ('Behavioural pharmacology', '1473-5849', ['Behavioral Sciences', 'Pharmacology']),
    ('Academic psychiatry : the journal of the American Association of Directors of Psychiatric Residency Training and the Association for Academic Psychiatry', '1545-7230', ['Psychiatry']),
    ('International review of psychiatry', '1369-1627', ['Psychiatry']),
    ('Psychiatria Danubina', '0353-5053', ['Psychiatry']),
    ('Development and psychopathology', '1469-2198', ['Psychiatry', 'Psychology']),
    ('Psychological assessment', '1939-134X', ['Psychology']),
    ('Psicothema', '1886-144X', ['Psychology']),
    ('Behavioural neurology', '1875-8584', ['Behavioral Sciences', 'Neurology']),
    ('Behavioral medicine', '1940-4026', ['Behavioral Sciences', 'Psychiatry']),
    ('Current opinion in psychiatry', '1473-6578', ['Psychiatry']),
    ('Irish journal of psychological medicine', '2051-6967', ['Psychiatry']),
    ('Schizophrenia research', '1573-2509', ['Psychiatry']),
    ('Journal of sport & exercise psychology', '1543-2904', ['Psychology', 'Sports Medicine']),
    ('Epilepsy research', '1872-6844', ['Brain', 'Neurology']),
    ('Research in developmental disabilities', '1873-3379', ['Psychiatry']),
    ('Journal of anxiety disorders', '1873-7897', ['Psychiatry']),
    ('Journal of personality disorders', '1943-2763', ['Psychiatry', 'Psychology']),
    ('Cognition & emotion', '1464-0600', ['Psychology']),
    ('Journal of family psychology : JFP : journal of the Division of Family Psychology of the American Psychological Association (Division 43)', '1939-1293', ['Psychology']),
    ('Journal of cognitive psychotherapy', '1938-887X', ['Psychology']),
    ('Psychology & health', '1476-8321', ['Psychology']),
    ('Psychology of addictive behaviors : journal of the Society of Psychologists in Addictive Behaviors', '1939-1501', ['Psychology', 'Substance-Related Disorders']),
    ('Journal of psychopharmacology', '1461-7285', ['Psychopharmacology']),
    ('Violence and victims', '0886-6708', ['Behavioral Sciences', 'Psychology']),
    ('Psychiatria Hungarica : A Magyar Pszichiátriai Társaság tudományos folyóirata', '0237-7896', ['Psychiatry']),
    ('Human psychopharmacology', '1099-1077', ['Psychopharmacology']),
    ('International clinical psychopharmacology', '1473-5857', ['Psychopharmacology']),
    ('Annals of behavioral medicine : a publication of the Society of Behavioral Medicine', '1532-4796', ['Behavioral Sciences']),
    ('Psychopathology', '1423-033X', ['Psychiatry']),
    ('Pharmacopsychiatry', '1439-0795', ['Psychiatry', 'Psychopharmacology']),
    ('Behavioral sciences & the law', '1099-0798', ['Behavioral Sciences', 'Jurisprudence']),
    ('Behavioral neuroscience', '1939-0084', ['Behavioral Sciences', 'Neurology']),
    ('Journal of comparative psychology', '1939-2087', ['Psychology']),
    ('Journal of reproductive and infant psychology', '1469-672X', ['Psychology', 'Reproductive Medicine']),
    ('International journal of psychophysiology : official journal of the International Organization of Psychophysiology', '1872-7697', ['Psychophysiology']),
    ('Brain and cognition', '1090-2147', ['Brain', 'Psychophysiology']),
    ('Progress in neuro-psychopharmacology & biological psychiatry', '1878-4216', ['Psychiatry', 'Psychopharmacology']),
    ('Journal of experimental psychology. Learning, memory, and cognition', '1939-1285', ['Psychology']),
    ('Health psychology : official journal of the Division of Health Psychology, American Psychological Association', '1930-7810', ['Psychology']),
    ('The International journal of eating disorders', '1098-108X', ['Behavioral Sciences']),
    ('The British journal of clinical psychology', '0144-6657', ['Psychology']),
    ('The British journal of social psychology', '2044-8309', ['Psychology']),
    ('Clinical psychology review', '1873-7811', ['Psychology']),
    ('Journal of clinical psychopharmacology', '1533-712X', ['Psychopharmacology']),
    ('Journal of psychoactive drugs', '2159-9777', ['Psychopharmacology', 'Substance-Related Disorders']),
    ('Crisis', '2151-2396', ['Behavioral Sciences']),
    ('Behavioural brain research', '1872-7549', ['Behavioral Sciences', 'Brain']),
    ('Appetite', '1095-8304', ['Behavioral Sciences', 'Nutritional Sciences']),
    ('Journal of developmental and behavioral pediatrics : JDBP', '1536-7312', ['Behavioral Sciences', 'Pediatrics']),
    ('Infant mental health journal', '1097-0355', ['Behavioral Sciences', 'Pediatrics', 'Psychology']),
    ('Psychotherapie, Psychosomatik, medizinische Psychologie', '1439-1058', ['Psychiatry']),
    ('Brain & development', '1872-7131', ['Brain', 'Pediatrics']),
    ('Canadian journal of psychiatry. Revue canadienne de psychiatrie', '1497-0015', ['Psychiatry']),
    ('Journal of affective disorders', '1573-2517', ['Psychiatry']),
    ('Psychiatry research', '1872-7123', ['Psychiatry']),
    ('Journal of marital and family therapy', '1752-0606', ['Psychiatry', 'Psychology', 'Therapeutics']),
    ('Journal of behavioral medicine', '1573-3521', ['Behavioral Sciences']),
    ('The Behavioral and brain sciences', '1469-1825', ['Behavioral Sciences', 'Brain', 'Neurology', 'Psychology']),
    ('Neuroscience and biobehavioral reviews', '1873-7528', ['Behavioral Sciences', 'Neurology']),
    ('Infant behavior & development', '1879-0453', ['Behavioral Sciences', 'Pediatrics']),
    ('The Psychiatric clinics of North America', '1558-3147', ['Psychiatry']),
    ('The Journal of clinical psychiatry', '1555-2101', ['Psychiatry']),
    ('Sleep', '1550-9109', ['Psychophysiology']),
    ('Law and human behavior', '1573-661X', ['Behavioral Sciences', 'Jurisprudence']),
    ('Behavior modification', '1552-4167', ['Behavioral Sciences', 'Psychiatry']),
    ('Cognitive science', '1551-6709', ['Psychology']),
    ('Behavioural processes', '1872-8308', ['Behavioral Sciences']),
    ('Suicide & life-threatening behavior', '1943-278X', ['Behavioral Sciences', 'Psychiatry']),
    ('Clinical neuropharmacology', '1537-162X', ['Psychopharmacology']),
    ('Psychopharmacology', '1432-2072', ['Psychopharmacology']),
    ('Addictive behaviors', '1873-6327', ['Behavioral Sciences', 'Substance-Related Disorders']),
    ('Journal of experimental psychology. General', '1939-2222', ['Psychology']),
    ('Journal of experimental psychology. Human perception and performance', '1939-1277', ['Psychology']),
    ('Personality & social psychology bulletin', '1552-7433', ['Psychology']),
    ('Aggressive behavior', '1098-2337', ['Behavioral Sciences']),
    ('Journal of homosexuality', '1540-3602', ['Behavioral Sciences']),
    ('Journal of sex & marital therapy', '1521-0715', ['Behavioral Sciences', 'Psychiatry']),
    ('Brain and language', '1090-2155', ['Brain', 'Psychophysiology', 'Speech-Language Pathology']),
    ('Psychiatrische Praxis', '1439-0876', ['Psychiatry']),
    ('Journal of child language', '1469-7602', ['Psychology']),
    ('Psychological research', '1430-2772', ['Psychology']),
    ('Pharmacology, biochemistry, and behavior', '1873-5177', ['Behavioral Sciences', 'Biochemistry', 'Pharmacology', 'Psychopharmacology']),
    ('No shinkei geka. Neurological surgery', '1882-1251', ['Brain', 'Neurosurgery']),
    ('International journal of psychiatry in medicine', '1541-3527', ['Psychiatry']),
    ('Memory & cognition', '1532-5946', ['Psychology']),
    ('American journal of community psychology', '1573-2770', ['Psychology']),
    ('Journal of community psychology', '1520-6629', ['Psychology']),
    ('Biological psychology', '1873-6246', ['Psychophysiology']),
    ('Journal of youth and adolescence', '1573-6601', ['Behavioral Sciences', 'Pediatrics', 'Psychology']),
    ('International journal of offender therapy and comparative criminology', '1552-6933', ['Behavioral Sciences', 'Therapeutics']),
    ('Tijdschrift voor psychiatrie', '0303-7339', ['Psychiatry']),
    ('Cognition', '1873-7838', ['Psychology']),
    ('Perception', '1468-4233', ['Psychology', 'Psychophysiology']),
    ('Archives of sexual behavior', '1573-2800', ['Behavioral Sciences', 'Psychiatry']),
    ('Journal of personality assessment', '1532-7752', ['Psychiatry', 'Psychology']),
    ('Journal of psycholinguistic research', '1573-6555', ['Psychology']),
    ('Behavior genetics', '1573-3297', ['Behavioral Sciences', 'Genetics']),
    ('Journal of behavior therapy and experimental psychiatry', '1873-7943', ['Behavioral Sciences', 'Psychiatry', 'Therapeutics']),
    ('Behavior therapy', '1878-1888', ['Behavioral Sciences', 'Therapeutics']),
    ('Psychological medicine', '1469-8978', ['Psychology']),
    ('Cognitive psychology', '1095-5623', ['Psychology']),
    ('Hormones and behavior', '1095-6867', ['Behavioral Sciences', 'Endocrinology']),
    ('Schizophrenia bulletin', '1745-1701', ['Psychiatry']),
    ('Biological psychiatry', '1873-2402', ['Psychiatry', 'Psychophysiology']),
    ('Applied ergonomics', '1872-9126', ['Psychology']),
    ('Journal of applied behavior analysis', '1938-3703', ['Behavioral Sciences']),
    ('Brain, behavior and evolution', '1421-9743', ['Behavioral Sciences', 'Biology', 'Brain']),
    ('Journal of consulting and clinical psychology', '1939-2117', ['Psychology']),
    ('Journal of learning disabilities', '1538-4780', ['Psychology']),
    ('Journal of health and social behavior', '2150-6000', ['Behavioral Sciences']),
    ('Psychiatria polska', '2391-5854', ['Psychiatry']),
    ('The Australian and New Zealand journal of psychiatry', '1440-1614', ['Psychiatry']),
    ('Physiology & behavior', '1873-507X', ['Behavioral Sciences', 'Physiology', 'Psychophysiology']),
    ('Multivariate behavioral research', '1532-7906', ['Behavioral Sciences', 'Psychology', 'Statistics as Topic']),
    ('International journal of psychology : Journal international de psychologie', '1464-066X', ['Psychology']),
    ('Psychopharmacology bulletin', '2472-2448', ['Psychopharmacology']),
    ('Journal of the history of the behavioral sciences', '1520-6696', ['Behavioral Sciences', 'History of Medicine']),
    ('Journal of sex research', '1559-8519', ['Behavioral Sciences', 'Reproductive Medicine']),
    ('Psychotherapy and psychosomatics', '1423-0348', ['Psychiatry', 'Therapeutics']),
    ('Community mental health journal', '1573-2789', ['Psychology']),
    ('Journal of personality and social psychology', '1939-1315', ['Psychology']),
    ('The British journal of mathematical and statistical psychology', '2044-8317', ['Psychology', 'Statistics as Topic']),
    ('Cortex; a journal devoted to the study of the nervous system and behavior', '1973-8102', ['Behavioral Sciences', 'Brain', 'Neurology']),
    ('Psychophysiology', '1469-8986', ['Psychophysiology']),
    ('Advances in child development and behavior', '0065-2407', ['Behavioral Sciences', 'Pediatrics']),
    ('Behaviour research and therapy', '1873-622X', ['Behavioral Sciences', 'Therapeutics']),
    ('Psychoanalytic review', '1943-3301', ['Psychiatry']),
    ('The British journal of psychiatry : the journal of mental science', '1472-1465', ['Psychiatry']),
    ('Psychotherapy', '1939-1536', ['Psychology', 'Therapeutics']),
    ('Acta psychiatrica Scandinavica', '1600-0447', ['Psychiatry']),
    ('Journal of psychiatric research', '1879-1379', ['Psychiatry']),
    ('Comprehensive psychiatry', '1532-8384', ['Psychiatry']),
    ('Rivista di psichiatria', '2038-2502', ['Psychiatry']),
    ('Journal of child psychology and psychiatry, and allied disciplines', '1469-7610', ['Psychiatry', 'Psychology']),
    ('Scandinavian journal of psychology', '1467-9450', ['Psychology']),
    ('The International journal of clinical and experimental hypnosis', '1744-5183', ['Psychology', 'Therapeutics']),
    ('Journal of the experimental analysis of behavior', '1938-3711', ['Behavioral Sciences']),
    ('Human factors', '1547-8181', ['Psychology']),
    ('The American journal of clinical hypnosis', '2160-0562', ['Psychology', 'Therapeutics']),
    ('Ergonomics', '1366-5847', ['Psychology']),
    ('Journal of psychosomatic research', '1879-1360', ['Psychiatry']),
    ('The International journal of social psychiatry', '1741-2854', ['Psychiatry']),
    ('Psychological reports', '1558-691X', ['Psychology']),
    ('The Journal of analytical psychology', '1468-5922', ['Psychology']),
    ('Perceptual and motor skills', '1558-688X', ['Psychology', 'Psychophysiology']),
    ('The Journal of genetic psychology', '1940-0896', ['Behavioral Sciences', 'Genetics', 'Psychology']),
    ('Journal of counseling psychology', '0022-0167', ['Psychology']),
    ('Journal of the American Psychoanalytic Association', '1941-2460', ['Psychiatry']),
    ('British journal of psychology', '2044-8295', ['Psychology']),
    ('International journal of group psychotherapy', '1943-2836', ['Psychiatry', 'Therapeutics']),
    ('Annual review of psychology', '1545-2085', ['Psychology']),
    ('American journal of psychotherapy', '2575-6559', ['Psychiatry', 'Therapeutics']),
    ('The American psychologist', '1935-990X', ['Psychology']),
    ('Journal of clinical psychology', '1097-4679', ['Psychology']),
    ('Journal of personality', '1467-6494', ['Psychology']),
    ('American journal of psychoanalysis', '1573-6741', ['Psychiatry']),
    ('Psychiatry', '1943-281X', ['Psychiatry']),
    ('Psychometrika', '1860-0980', ['Behavioral Sciences']),
    ('Bulletin of the Menninger Clinic', '1943-2828', ['Psychiatry']),
    ('Acta psychologica', '1873-6297', ['Psychology']),
    ('The Journal of psychology', '1940-1019', ['Psychology']),
    ('The Psychoanalytic quarterly', '2167-4086', ['Psychiatry']),
    ('The American journal of orthopsychiatry', '1939-0025', ['Psychiatry', 'Psychology']),
    ('The Journal of social psychology', '1940-1183', ['Psychology']),
    ('The Journal of general psychology', '1940-0888', ['Psychology']),
    ('The Psychiatric quarterly', '1573-6709', ['Psychiatry']),
    ('The American journal of psychiatry', '1535-7228', ['Psychiatry']),
    ('The International journal of psycho-analysis', '1745-8315', ['Psychiatry']),
    ('The Journal of applied psychology', '1939-1854', ['Psychology']),
    ('Epilepsia', '1528-1167', ['Brain', 'Neurology']),
    ('Psychological bulletin', '1939-1455', ['Psychology']),
    ('Psychological review', '1939-1471', ['Psychology']),
    ('Brain : a journal of neurology', '1460-2156', ['Brain', 'Neurology']),
]

ISSNS: list[str] = [issn for _, issn, _ in MIND_JOURNALS]

CATEGORIES: list[str] = sorted({c for _, _, cats in MIND_JOURNALS for c in cats})
